config/routes.rb
Force::Application.routes.draw do

  resources :users
  resources :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :validate, :only => :create

  def index
    @tasks = Task.all()[0..19]
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(params[:task])
    task.IsRecurrence = false
    task.IsReminderSet = false
    task.Priority = "Normal"
    user = User.first
    task.OwnerId = user.Id
    begin
      if (task.save)
        redirect_to(task, :notice => 'Task was successfully created.')
      end
    rescue Databasedotcom::SalesForceError => e
      redirect_to(tasks_path, :notice => "Error creating task: #{e.message}")
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.delete
    redirect_to(tasks_path, :notice => "Task '#{task.Subject}' was successfully deleted.")
  end

  private

  def validate
    @task = Task.new(params[:task])
    flash[:notice] = "Error"
    render :action => :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Databasedotcom::Rails::Controller

  def index
    #@users = User.all()[0..19]
    @users = User.query("Id != NULL LIMIT 20")
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    render "show"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if (@user.save)
      redirect_to(@user, :notice => 'User was successfully created.')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Force</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%=  link_to "Add New Task", new_task_path %>
<br/>
<br/>

<% @tasks.each do |task| %>
  <%= link_to "#{task.Subject}", task %><br/>
<% end %>

app/views/tasks/new.html.erb
<h1>Create task</h1>

<% if flash[:notice] %>
  <%= flash[:notice] %><br/><br/>
<% end %>

<%= form_for @task do |f| %>
    <div class="field">
        <%= f.label :Subject %><br />
        <%= f.text_field :Subject %>
    </div>
    <div class="field">
        <%= f.label "Status" %>
        <%= f.select :Status, options_for_select([['Not Started', 'Not Started'], ['In Progress', 'In Progress'], ['Completed','Completed']]) %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>Task <%= @task.Subject %></h1>

<%= link_to 'Back', tasks_path %> | <%= link_to 'Delete', @task, :confirm => 'Are You Sure?', :method => :delete %>
<br/>
<br/>

<% @task.attributes.each do |a| %>
    <%= a[0] %>: <%= a[1] %><br/>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for @user do |f| %>
    <div class="field">
        <%= f.label :CompanyName %><br />
        <%= f.text_field :CompanyName %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |u| %>
  <%= link_to "#{u.Name}", u %> (<%= link_to "Edit", edit_user_path(u) %>)<br/>
<% end %>

app/views/users/new.html.erb
<h1>Create user</h1>

<%= form_for @user do |f| %>
    <div class="field">
        <%= f.label :Name %><br />
        <%= f.text_field :Name %>
    </div>
    <div class="field">
        <%= f.label :CompanyName %><br />
        <%= f.text_field :CompanyName %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<br/>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User <%= @user.Name %></h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<br/>
<br/>

<% @user.attributes.each do |a| %>
    <%= a[0] %>: <%= a[1] %><br/>
<% end %>